# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "windows_2012_r2"

  config.ssh.insert_key = false

  config.vm.network "forwarded_port", host: 5985, guest: 5985

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end
end
